---
name: "Deploy"

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
    uses: timmo001/workflows/.github/workflows/deploy-python-linux.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    with:
      module-name: systembridgegui
      pre-install-command: |
        sudo apt update
        sudo apt install libegl-dev libpulse0
      use-incremental: true
