---
name: "Deploy"

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    uses: timmo001/workflows/.github/workflows/deploy-python-linux.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    with:
      module-name: systembridgegui
      pre-install-command: |
        sudo apt update
        sudo apt install libegl-dev libpulse0
        pip install --upgrade --pre systembridgeshared
        pip install .
      use-incremental: true
